version: '3'
services:
  project-db:
    container_name: morningstar-db
    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "3307:3306"
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 30s
      retries: 3
    networks:
      - network

  redis:
    container_name: morningstar-redis
    image: redis:7-alpine # 경량화된 alpine 버전을 사용합니다.
    ports:
      - "6379:6379" # Redis 기본 포트를 매핑합니다.
    restart: always
    networks:
      - morningstar-network

networks:
  network: