version: '3.8'

services:
  # Spring Boot 애플리케이션 서비스
  spring-app:
    image: liyusang97/project:latest
    container_name: project-container
    ports:
      - "8080:8080"

    volumes:
      - ./logs:/app/logs
      - ./.env:/.env

    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: job=morningstar-spring,env=prod

    environment:
      - SPRING_DATA_REDIS_HOST=redis

    depends_on:
      redis:
        condition: service_healthy

    networks:
      - morningstar-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    volumes:
      - redis-data:/data
    networks:
      - morningstar-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  morningstar-network:

volumes:
  redis-data:
