version: '3.8'

services:
  # Spring Boot 애플리케이션 서비스
  spring-app:
    image: liyusang97/project:latest
    container_name: project-container
    ports:
      - "8080:8080"

    volumes:
      # 기존 로그 마운트 설정
      - ./logs:/app/logs
      # EC2 서버의 .env 파일을 컨테이너의 루트(/) 디렉터리에 .env 파일로 연결합니다.
      - ./.env:/.env

    environment:
      - SPRING_DATA_REDIS_HOST=redis

    depends_on:
      redis:
        condition: service_healthy

    networks:
      - morningstar-network

  # Redis
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    volumes:
      - redis-data:/data
    networks:
      - morningstar-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  morningstar-network:

volumes:
  redis-data:
