server:
  port: 8080
  error:
    include-message: always
  forward-headers-strategy: NATIVE

spring:
  servlet:
    multipart:
      max-file-size: 5MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_KEY}
            scope:
              - email
              - profile
            redirect-uri: "https://gaebang.site/login/oauth2/code/google"
          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_KEY}
            client-authentication-method: client_secret_post
            redirect-uri: https://gaebang.site/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  # 캐시 활성화 (성능상 필요)
  cache:
    type: simple
    cache-names:
      - "ai-responses"
      - "vector-search-results"

  # 배치 자동 실행 방지 (필수)
  batch:
    job:
      enabled: false

# ChromaDB 벡터 데이터베이스 (필수)
chroma:
  base-url: http://localhost:8000

# WebSocket 실시간 통신 (필수)
websocket:
  endpoint: "/ws/interview"
  allowed-origins:
    - "http://localhost:3000"
    - "http://localhost:8080"
