spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
      idle-timeout: 600000   # 10분
      max-lifetime: 1800000  # 30분

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect
      # OSIV(Open Session In View)를 비활성화하여 성능을 최적화
      open-in-view: false

logging:
  # [추가] 로그 파일을 저장할 경로와 파일 이름 설정
  file:
    # 이 경로에 logs 폴더가 없으면 Spring Boot가 자동으로 생성합니다.
    path: ./logs
    name: app.log

  level:
    # [변경] 전반적인 로그 레벨을 INFO로 설정
    root: INFO
    # [변경] Security 로그를 DEBUG에서 INFO로 변경하여 과도한 로그 생성을 방지.
    org.springframework.security: INFO
    # [추가] Hibernate 관련 로그 레벨을 WARN으로 설정하여 불필요한 INFO 로그를 줄임.
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health"
