server:
  port: 8080
  error:
    include-message: always
  forward-headers-strategy: NATIVE

spring:
  servlet:
    multipart:
      max-file-size: 5MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET_KEY}
            scope:
              - email
              - profile
            redirect-uri: "https://gaebang.site/login/oauth2/code/google"
          kakao:
            client-id: ${KAKAO_ID}
            client-secret: ${KAKAO_KEY}
            client-authentication-method: client_secret_post
            redirect-uri: https://gaebang.site/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id