### 로그인
# @name login_2fa
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "test2@naver.com",
  "password": 123456
}
> {%
    if (response.body && response.body.data) {
        client.global.set("authToken", response.body.data.token)
    } else {
        client.global.set("authToken", "")
    }
%}

### Test JWT
GET http://localhost:8080/member/test/jwt
Authorization: {{authToken}}
Content-Type: application/json

### 비밀번호 변경
PATCH http://localhost:8080/member/password
Authorization: {{authToken}}
Content-Type: application/json

{
  "currentPassword": "123456",
  "newPassword": "1234567"
}

### 닉네임변경
PATCH http://localhost:8080/member/nickname
Authorization: {{authToken}}
Content-Type: application/json

{
  "nickname": "변경된닉네임"
}

### 회원탈퇴
DELETE http://localhost:8080/member
Authorization: {{authToken}}
Content-Type: application/json

### 이메일 중복체크
GET http://localhost:8080/member/check-duplicated-email?email=test1@naver.com

